general:
  img_size: 228

model:
  architecture: resnet18
  pretrained: True
  num_classes: 3000

training:
  optimizer: adam
  learning_rate: 0.0001
  max_epochs: 3
  save_checkpoint_every: 3
  early_stopping_patience: 8
  model_path: "./saved_models/"
  loss_function: "triplet"

train_dataset:
  data_root: './train_gallery/'
  batch_size: 4

test_dataset:
  data_root: './test_gallery/'
  batch_size: 1

competition_code:
  data_root: './comp_data/'