general:
  img_size: 228
  project_name: "model_selection"

model:
  architecture: resnet18
  pretrained: True
  num_classes: 3000

training:
  optimizer: adam
  learning_rate: 0.0001
  max_epochs: 20
  save_checkpoint_every: 3
  early_stopping_patience: 8
  model_path: "./saved_models/"
  loss_function: "triplet"

train_dataset:
  data_root: './train_gallery/'
  batch_size: 128

test_dataset:
  data_root: './test_gallery/'
  batch_size: 1