wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: ResNet18
dataset:
  desc: null
  value: UTKFace
dataset_size:
  desc: null
  value: 544
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 128
device:
  desc: null
  value: cuda
loss:
  desc: null
  value: triplet
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684242720.816135
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.0
      5: 0.15.1
      8:
      - 3
      - 5
